### ISSUE TITLE
Structure view does not use the same encoding as Raw view.

### ISSUE THREAD

**Issue by vanlooverenkoen** [icapps/niddler-ui#24]
Structure view does not use the same encoding as Raw view when using url encoded. `:` wil be parsed to `%3A`
```
ipnsToken=dx1LdyrDwys%3AAPA91bEHJCF-ftZ5re1XQjAoiKuNfgwAMBd7L6IPq3Feyy1cKrjnICUOlb27Xi2LAl1JK4JZ5zLqmWZB35DJMiK1JXoJ8OP9xfLVvfLh8G_bp5sXpBURjdWCvr9OESgobVIXVbAmGb7Mepsgku130Io1P1KPrAlAdQ
```
![image](https://user-images.githubusercontent.com/21172855/42746826-0271fd28-88da-11e8-9fd7-4072732f52e1.png)

**Comment by NicolaChimerapps** [comment]
This is because the structure view shows the decoded values as opposed to the raw view which shows the raw body as sent 'over the wire'
