### ISSUE TITLE
How do I connect the device?

### ISSUE THREAD

**Issue by MarxZhou** [icapps/niddler-ui#42]
I installed this plugin in webstorm, but it is not clear how to connect the device and use it.
I am working on an app based on react native and I don't know much about native development.
Is there a tutorial you can refer to?
![image](https://user-images.githubusercontent.com/39861054/76000874-47c6a300-5f3f-11ea-9910-43275698d128.png)

**Comment by NicolaChimerapps** [comment]
This plugin requires the application to use the niddler mobile library. There is one for native android/java (https://github.com/icapps/niddler) and one for dart (https://github.com/Chimerapps/niddler_dart). Unfortunately, there is no library created for react-native yet
